# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build src\MessagePack.WebApi.Client.sln  --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
 
