# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build ./src/MessagePack.WebApi.Client.sln  --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: 'drop'
    Contents: './src/MessagePack.WebApi.Client/bin/Release/*'
    ArtifactName: 'buildOutput'
    ArtifactType: 'Container'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
