// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.MsgPackBlazor.Shared
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class ContactFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MsgPackBlazor.Shared.Contact>
    {


        public void Serialize(ref MessagePackWriter writer, global::MsgPackBlazor.Shared.Contact value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(7);
            writer.Write(value.Id);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.FirstName, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.LastName, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.EmailAdress, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.PhoneNumber, options);
            formatterResolver.GetFormatterWithVerify<global::MsgPackBlazor.Shared.Genders>().Serialize(ref writer, value.Gender, options);
            formatterResolver.GetFormatterWithVerify<global::MsgPackBlazor.Shared.PostAddress>().Serialize(ref writer, value.StandardAddress, options);
        }

        public global::MsgPackBlazor.Shared.Contact Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Id__ = default(int);
            var __FirstName__ = default(string);
            var __LastName__ = default(string);
            var __EmailAdress__ = default(string);
            var __PhoneNumber__ = default(string);
            var __Gender__ = default(global::MsgPackBlazor.Shared.Genders);
            var __StandardAddress__ = default(global::MsgPackBlazor.Shared.PostAddress);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __Id__ = reader.ReadInt32();
                        break;
                    case 1:
                        __FirstName__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __LastName__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __EmailAdress__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 4:
                        __PhoneNumber__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 5:
                        __Gender__ = formatterResolver.GetFormatterWithVerify<global::MsgPackBlazor.Shared.Genders>().Deserialize(ref reader, options);
                        break;
                    case 6:
                        __StandardAddress__ = formatterResolver.GetFormatterWithVerify<global::MsgPackBlazor.Shared.PostAddress>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::MsgPackBlazor.Shared.Contact();
            ____result.Id = __Id__;
            ____result.FirstName = __FirstName__;
            ____result.LastName = __LastName__;
            ____result.EmailAdress = __EmailAdress__;
            ____result.PhoneNumber = __PhoneNumber__;
            ____result.Gender = __Gender__;
            ____result.StandardAddress = __StandardAddress__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
